AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR repository

Resources:
  ApiRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: api
  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: frontend
  WorkerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: worker